version: '3.9'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.0
    environment:
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx4096m"
      - discovery.type=single-node
      - xpack.security.enabled=false
      - search.max_async_search_response_size=2500000000b
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9200"]
        interval: 10s
        timeout: 2s
        retries: 10
        start_period: 30s
    volumes:
      - ./data:/usr/share/elasticsearch/data
    expose:
      - 9200
    ports:
      - 9200:9200
    networks:
      - net

  kibana:
    depends_on:
      - elastic
    image: docker.elastic.co/kibana/kibana:8.3.0
    expose:
      - 5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
      - REPORTING_CSV_MAXSIZEBYTES=2500000000
      - XPACK_REPORTING_CSV_MAXSIZEBYTES=2500000000
    networks:
      - net
      
  nginx:
    depends_on:
      - kibana
    image: nginx:latest
    ports: 
      - 80:80
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/www/:/var/www/:rw
    networks:
      - net

networks:
  net: